[project]
name = "purchase-intent"
version = "1.0.0-dev"
description = "Big data project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "jupyter>=1.1.1",
  "pandas-profiling>=3.6.6",
  "pyspark-client==4.0.1",
  "ucimlrepo>=0.0.7",
  "ydata-profiling>=4.18.0",
]
