services:
  spark-master:
    build: .
    hostname: spark-master
    ports:
      - "7077:7077"      # Spark master port
      - "8080:8080"      # Spark master web UI
      - "4040:4040"      # Spark application web UI
      - "15002:15002"    # Spark Connect port
    volumes:
      - ./data/worker1:/opt/spark/data/worker1
      - ./data/worker2:/opt/spark/data/worker2
    command: >
      bash -c "/opt/spark/sbin/start-master.sh;
      sleep 5;
      /opt/spark/sbin/start-connect-server.sh --master spark://spark-master:7077 --conf spark.submit.deployMode=client;
      sleep infinity"
    networks:
      - spark-network
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: '0.5'
    

  spark-worker-1:
    build: .
    hostname: spark-worker-1
    ports:
      - "8081:8081"    # Spark worker web UI
    volumes:
      - ./data/worker1:/opt/spark/data/worker1
      - ./data/worker2:/opt/spark/data/worker2
    depends_on:
      - spark-master
    command: >
      bash -c "sleep 10;
               /opt/spark/sbin/start-worker.sh spark://spark-master:7077;
               sleep infinity"
    networks:
      - spark-network
    deploy:
      resources:
        limits:
          memory: 1000M
          cpus: '1'

  spark-worker-2:
    build: .
    hostname: spark-worker-2
    ports:
      - "8082:8081"    # Spark worker web UI (mapped to different host port)
    volumes:
      - ./data/worker1:/opt/spark/data/worker1
      - ./data/worker2:/opt/spark/data/worker2
    depends_on:
      - spark-master
    command: >
      bash -c "sleep 10;
               /opt/spark/sbin/start-worker.sh spark://spark-master:7077;
               sleep infinity"
    networks:
      - spark-network
    deploy:
      resources:
        limits:
          memory: 1000M
          cpus: '1'

volumes:
  master-data:
  worker1-data:
  worker2-data:

networks:
  spark-network:
    driver: bridge