services:
  spark-master:
    build: .
    hostname: spark-master
    ports:
      - "7077:7077"      # Spark master port
      - "8080:8080"      # Spark master web UI
      - "4040:4040"      # Spark application web UI
      - "8888:8888"      # Jupyter notebook
      - "15002:15002"    # Spark Connect port
    volumes:
      - ./data/worker1:/opt/spark/data/worker1
      - ./data/worker2:/opt/spark/data/worker2
    command: >
      bash -c "/opt/spark/sbin/start-connect-server.sh;
               sleep infinity"
    networks:
      - spark-network
    

  spark-worker-1:
    build: .
    hostname: spark-worker-1
    ports:
      - "8081:8081"    # Spark worker web UI
    volumes:
      - ./data/worker1:/opt/spark/data/worker1  # Only worker1's data
    depends_on:
      - spark-master
    command: >
      bash -c "sleep 10;
               /opt/spark/sbin/start-worker.sh spark://spark-master:7077;
               sleep infinity"
    networks:
      - spark-network

  spark-worker-2:
    build: .
    hostname: spark-worker-2
    ports:
      - "8082:8081"    # Spark worker web UI (mapped to different host port)
    volumes:
      - ./data/worker2:/opt/spark/data/worker2  # Only worker2's data
    depends_on:
      - spark-master
    command: >
      bash -c "sleep 10;
               /opt/spark/sbin/start-worker.sh spark://spark-master:7077;
               sleep infinity"
    networks:
      - spark-network

volumes:
  master-data:
  worker1-data:
  worker2-data:

networks:
  spark-network:
    driver: bridge

deploy: 
  resources:
    limits:
      memory: 2500M
      cpus: '2.5'